### PR TITLE
Move site and hugo data into one repo

### PR DESCRIPTION
**Pull request by Alanocallaghan**

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
For this to work, you would have to merge and then go to settings and change the directory from which the site is published to the "docs" folder on the master branch

**Comment by Alanocallaghan** [comment]
No worries! I'll see if I can't make it work a slightly easier way

**Comment by catavallejos** [comment]
No problem. I think the issue is how the hugo websites are setup. Anyway, good night! Have a nice weekend!

**Comment by Alanocallaghan** [comment]
You too! 11pm on a Friday is not the right time to merge code anyway :)

**Pull request merged**
